--MySQL存储过程样例 ↓
BEGIN
DECLARE tabName VARCHAR(128) DEFAULT '';
DECLARE sqlStr VARCHAR(255) DEFAULT '';
DECLARE tabCount INT DEFAULT 0;
WHILE tabCount < 5 DO
SELECT TABLE_NAME INTO tabName FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'idc_pick_compare%' LIMIT tabCount,1;
SET @sqlStr = CONCAT(CONCAT('DELETE FROM `',tabName),'` WHERE value_in_minus = 0 OR value_out_minus = 0');
PREPARE STMT FROM @sqlStr;
EXECUTE STMT;
SET tabCount = tabCount + 1;
END WHILE;
END;
--Oracle存储过程样例 ↓
CREATE OR REPLACE
PROCEDURE LOOP_TWO_TOOL IS
monthStr VARCHAR2(3);
loopCount NUMBER;
countSQL VARCHAR2(256);
exeSQL VARCHAR2(256);
BEGIN
FOR i IN 2..12 LOOP
	IF i<10 THEN monthStr:= CONCAT('0',i);
	ELSIF i>9 THEN monthStr:= i;
	END IF;
	countSQL:= CONCAT('SELECT CEIL (COUNT(1) / 50) FROM NET_CAP_PORT_2021_',CONCAT(monthStr,' WHERE ROUTID IS NULL'));
	EXECUTE IMMEDIATE countSQL INTO loopCount;
	exeSQL:= CONCAT('UPDATE NET_CAP_PORT_2021_',CONCAT(monthStr,' NCP SET NCP.ROUTID =(SELECT IBD.DEVICE_ID FROM IDC_BASE_DEVICE IBD WHERE NCP.ROUTNAME = IBD.DEV_ID) WHERE NCP.ROUTID IS NULL AND ROWNUM <= 50'));
	FOR j IN 1..loopCount LOOP
		EXECUTE IMMEDIATE exeSQL;
		COMMIT;
	END LOOP;
END LOOP;
END;
--MySQL删除表格忽略外键 ↓
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS 'table_name';
SET FOREIGN_KEY_CHECKS = 1;